# Generated by Django 3.0 on 2020-11-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='year',
            field=models.CharField(default=2008, max_length=4),
            preserve_default=False,
        ),
    ]
