# Generated by Django 3.0 on 2020-11-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_photo_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
